In [1]:
import os
import pandas

# Construction du csv emotion

In [2]:
FOLDER_EMOTION = "sentence_level_all_features"
FOLDER_EMOTION_UTF8 = "sentence_level_all_features_utf8"

In [3]:
# Conversion des fichiers MBCS -> UTF-8
os.makedirs(FOLDER_EMOTION_UTF8, exist_ok=True)

converted = 0
errors = []
for filename in os.listdir(FOLDER_EMOTION):
    if not filename.endswith(".txt"):
        continue
    src_path = os.path.join(FOLDER_EMOTION, filename)
    dst_path = os.path.join(FOLDER_EMOTION_UTF8, filename)
    try:
        with open(src_path, "r", encoding="mbcs") as f:
            content = f.read()
        with open(dst_path, "w", encoding="utf-8") as f:
            f.write(content)
        converted += 1
    except Exception as e:
        errors.append((filename, str(e)))

print(f"{converted} fichier(s) converti(s) en UTF-8.")
if errors:
    print(f"{len(errors)} erreur(s) :", errors)

2896 fichier(s) converti(s) en UTF-8.

In [4]:


FOLDER_EMOTION = FOLDER_EMOTION_UTF8
features_found = set()

for filename in os.listdir(FOLDER_EMOTION):
    if not filename.endswith(".txt"):
        continue
    filepath = os.path.join(FOLDER_EMOTION, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if "::" in line:
                feature_name = line.split("::")[0].strip()
                if feature_name and feature_name != "Features":
                    features_found.add(feature_name)

print(f"{len(features_found)} features uniques trouvées :\n")
for feat in sorted(features_found):
    print(f"  - {feat}")

16 features uniques trouvées :

  - avec_cat_admiration
  - avec_cat_autre
  - avec_cat_colere
  - avec_cat_embarras
  - avec_cat_fierte
  - avec_cat_joie
  - avec_cat_peur
  - avec_cat_surprise
  - avec_cat_tristesse
  - avec_emo
  - avec_emo_base
  - avec_emo_complexe
  - avec_emo_comportementale
  - avec_emo_designee
  - avec_emo_montree
  - avec_emo_suggeree

In [5]:
type(features_found)

set

In [6]:
NO_FEATURES_MESSAGE ="No features found."
ALL_FEATURES = list(features_found)

In [7]:
def extract_text(lines):
    if lines[-1]!=NO_FEATURES_MESSAGE:
     l = len(lines)
     trueline = []
     i = 4
     while True:
        if lines[i].startswith("Features::"):
            break
        trueline.append(lines[i])
        i+=1
        return " ".join(trueline).strip().split("Sentence: ")[1].strip()
    else:
     return " ".join(lines[4:-1]).strip().split("Sentence: ")[1].strip()


def extract_features(lines):
    features = {}
    for line in lines:
        line = line.strip()
        if "::" in line:
            parts = line.split("::")
            feature_name = parts[0].strip()
            if feature_name in ALL_FEATURES:
                features[feature_name] = 1
    return features


def extract_from_file(lines, id):

    row = {"file_id": id, "feature_found": False}
    for f in ALL_FEATURES:
        row[f] = 0

    if lines[-1].strip() == NO_FEATURES_MESSAGE:
        print("No features found for file id: ", id)
        row["text"] = ("\n").join(lines[3:-1]).split("Sentence: ")[1].strip()
    else:
        row["text"] = extract_text(lines)
        row["feature_found"] = True
        found = extract_features(lines)
        for fname, val in found.items():
            row[fname] = val

    return row

In [8]:
rows = []

for filename in os.listdir(FOLDER_EMOTION):
    if not filename.endswith(".txt"):
        continue
    file_id = filename.replace(".txt", "")
    filepath = os.path.join(FOLDER_EMOTION, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()
    # On filtre les lignes vides en fin de fichier
    while lines and lines[-1].strip() == "":
        lines.pop()
    rows.append(extract_from_file(lines, file_id))

No features found for file id:  100
No features found for file id:  1002
No features found for file id:  1003
No features found for file id:  1004
No features found for file id:  1005
No features found for file id:  1007
No features found for file id:  1008
No features found for file id:  1009
No features found for file id:  101
No features found for file id:  1010
No features found for file id:  1011
No features found for file id:  1012
No features found for file id:  1013
No features found for file id:  1014
No features found for file id:  1015
No features found for file id:  1016
No features found for file id:  1019
No features found for file id:  102
No features found for file id:  1020
No features found for file id:  1022
No features found for file id:  1024
No features found for file id:  1025
No features found for file id:  1026
No features found for file id:  1027
No features found for file id:  1028
No features found for file id:  1029
No features found for file id:  1030
No features found for file id:  1031
No features found for file id:  1032
No features found for file id:  1033
No features found for file id:  1036
No features found for file id:  1037
No features found for file id:  1038
No features found for file id:  1039
No features found for file id:  1040
No features found for file id:  1041
No features found for file id:  1042
No features found for file id:  1044
No features found for file id:  1045
No features found for file id:  1047
No features found for file id:  1048
No features found for file id:  105
No features found for file id:  1050
No features found for file id:  1051
No features found for file id:  1052
No features found for file id:  1055
No features found for file id:  1056
No features found for file id:  1057
No features found for file id:  1058
No features found for file id:  1059
No features found for file id:  106
No features found for file id:  1063
No features found for file id:  1066
No features found for file id:  1067
No features found for file id:  1068
No features found for file id:  107
No features found for file id:  1071
No features found for file id:  1072
No features found for file id:  1074
No features found for file id:  1075
No features found for file id:  1077
No features found for file id:  1078
No features found for file id:  1079
No features found for file id:  108
No features found for file id:  1080
No features found for file id:  1081
No features found for file id:  1082
No features found for file id:  1083
No features found for file id:  1084
No features found for file id:  1085
No features found for file id:  1086
No features found for file id:  1087
No features found for file id:  1088
No features found for file id:  1089
No features found for file id:  109
No features found for file id:  1091
No features found for file id:  1092
No features found for file id:  1093
No features found for file id:  1094
No features found for file id:  1096
No features found for file id:  1097
No features found for file id:  1098
No features found for file id:  1099
No features found for file id:  11
No features found for file id:  1100
No features found for file id:  1101
No features found for file id:  1102
No features found for file id:  1104
No features found for file id:  1106
No features found for file id:  1108
No features found for file id:  111
No features found for file id:  1112
No features found for file id:  1115
No features found for file id:  1117
No features found for file id:  1118
No features found for file id:  1119
No features found for file id:  112
No features found for file id:  1120
No features found for file id:  1121
No features found for file id:  1122
No features found for file id:  1123
No features found for file id:  1124
No features found for file id:  1126
No features found for file id:  1127
No features found for file id:  1129
No features found for file id:  113
No features found for file id:  1130
No features found for file id:  1131
No features found for file id:  1132
No features found for file id:  1133
No features found for file id:  1134
No features found for file id:  1135
No features found for file id:  1136
No features found for file id:  1137
No features found for file id:  1138
No features found for file id:  114
No features found for file id:  1140
No features found for file id:  1141
No features found for file id:  1142
No features found for file id:  1143
No features found for file id:  1144
No features found for file id:  1145
No features found for file id:  1147
No features found for file id:  1148
No features found for file id:  115
No features found for file id:  1150
No features found for file id:  1151
No features found for file id:  1152
No features found for file id:  1153
No features found for file id:  1154
No features found for file id:  1155
No features found for file id:  1156
No features found for file id:  1158
No features found for file id:  1159
No features found for file id:  116
No features found for file id:  1160
No features found for file id:  1161
No features found for file id:  1162
No features found for file id:  1163
No features found for file id:  1164
No features found for file id:  1165
No features found for file id:  1166
No features found for file id:  1167
No features found for file id:  1168
No features found for file id:  1169
No features found for file id:  1171
No features found for file id:  1173
No features found for file id:  1174
No features found for file id:  1175
No features found for file id:  1176
No features found for file id:  1177
No features found for file id:  1178
No features found for file id:  1179
No features found for file id:  118
No features found for file id:  1180
No features found for file id:  1181
No features found for file id:  1182
No features found for file id:  1183
No features found for file id:  1185
No features found for file id:  1186
No features found for file id:  1187
No features found for file id:  1188
No features found for file id:  1189
No features found for file id:  1190
No features found for file id:  1192
No features found for file id:  1193
No features found for file id:  1194
No features found for file id:  1195
No features found for file id:  1197
No features found for file id:  1198
No features found for file id:  1199
No features found for file id:  120
No features found for file id:  1201
No features found for file id:  1203
No features found for file id:  1205
No features found for file id:  1207
No features found for file id:  1209
No features found for file id:  121
No features found for file id:  1210
No features found for file id:  1212
No features found for file id:  1214
No features found for file id:  1215
No features found for file id:  1216
No features found for file id:  1217
No features found for file id:  1218
No features found for file id:  1219
No features found for file id:  122
No features found for file id:  1220
No features found for file id:  1221
No features found for file id:  1222
No features found for file id:  1223
No features found for file id:  1224
No features found for file id:  1227
No features found for file id:  123
No features found for file id:  1230
No features found for file id:  1231
No features found for file id:  1232
No features found for file id:  1233
No features found for file id:  1234
No features found for file id:  1235
No features found for file id:  1236
No features found for file id:  1238
No features found for file id:  1239
No features found for file id:  124
No features found for file id:  1241
No features found for file id:  1243
No features found for file id:  1244
No features found for file id:  1245
No features found for file id:  1246
No features found for file id:  1247
No features found for file id:  1248
No features found for file id:  1249
No features found for file id:  125
No features found for file id:  1251
No features found for file id:  1252
No features found for file id:  1253
No features found for file id:  1254
No features found for file id:  1255
No features found for file id:  1256
No features found for file id:  1257
No features found for file id:  1258
No features found for file id:  1259
No features found for file id:  126
No features found for file id:  1260
No features found for file id:  1261
No features found for file id:  1262
No features found for file id:  1263
No features found for file id:  1265
No features found for file id:  1266
No features found for file id:  1267
No features found for file id:  1268
No features found for file id:  127
No features found for file id:  1270
No features found for file id:  1271
No features found for file id:  1272
No features found for file id:  1273
No features found for file id:  1274
No features found for file id:  1276
No features found for file id:  1277
No features found for file id:  1278
No features found for file id:  1279
No features found for file id:  128
No features found for file id:  1280
No features found for file id:  1281
No features found for file id:  1283
No features found for file id:  1284
No features found for file id:  1287
No features found for file id:  129
No features found for file id:  1290
No features found for file id:  1292
No features found for file id:  1293
No features found for file id:  1295
No features found for file id:  1296
No features found for file id:  1297
No features found for file id:  1298
No features found for file id:  1299
No features found for file id:  130
No features found for file id:  1300
No features found for file id:  1301
No features found for file id:  1302
No features found for file id:  1304
No features found for file id:  1305
No features found for file id:  1306
No features found for file id:  1307
No features found for file id:  1308
No features found for file id:  131
No features found for file id:  1312
No features found for file id:  1313
No features found for file id:  1314
No features found for file id:  1315
No features found for file id:  1316
No features found for file id:  1317
No features found for file id:  1318
No features found for file id:  1321
No features found for file id:  1322
No features found for file id:  1323
No features found for file id:  1325
No features found for file id:  1326
No features found for file id:  1327
No features found for file id:  1328
No features found for file id:  1329
No features found for file id:  133
No features found for file id:  1331
No features found for file id:  1334
No features found for file id:  1335
No features found for file id:  1338
No features found for file id:  1339
No features found for file id:  1341
No features found for file id:  1342
No features found for file id:  1343
No features found for file id:  1344
No features found for file id:  1345
No features found for file id:  1346
No features found for file id:  1347
No features found for file id:  1348
No features found for file id:  1349
No features found for file id:  1350
No features found for file id:  1351
No features found for file id:  1352
No features found for file id:  1354
No features found for file id:  1355
No features found for file id:  1356
No features found for file id:  1357
No features found for file id:  1358
No features found for file id:  1359
No features found for file id:  1360
No features found for file id:  1361
No features found for file id:  1363
No features found for file id:  1365
No features found for file id:  1366
No features found for file id:  1369
No features found for file id:  137
No features found for file id:  1370
No features found for file id:  1372
No features found for file id:  1373
No features found for file id:  1374
No features found for file id:  1375
No features found for file id:  1376
No features found for file id:  1378
No features found for file id:  1379
No features found for file id:  138
No features found for file id:  1382
No features found for file id:  1383
No features found for file id:  1384
No features found for file id:  1385
No features found for file id:  1386
No features found for file id:  1387
No features found for file id:  1388
No features found for file id:  1389
No features found for file id:  139
No features found for file id:  1390
No features found for file id:  1391
No features found for file id:  1392
No features found for file id:  1393
No features found for file id:  1394
No features found for file id:  1395
No features found for file id:  1396
No features found for file id:  1397
No features found for file id:  1398
No features found for file id:  1399
No features found for file id:  14
No features found for file id:  140
No features found for file id:  1400
No features found for file id:  1401
No features found for file id:  1402
No features found for file id:  1403
No features found for file id:  1404
No features found for file id:  1405
No features found for file id:  1406
No features found for file id:  1407
No features found for file id:  1408
No features found for file id:  1409
No features found for file id:  141
No features found for file id:  1410
No features found for file id:  1414
No features found for file id:  1416
No features found for file id:  1418
No features found for file id:  1419
No features found for file id:  142
No features found for file id:  1420
No features found for file id:  1421
No features found for file id:  1422
No features found for file id:  1423
No features found for file id:  1424
No features found for file id:  1425
No features found for file id:  1426
No features found for file id:  1427
No features found for file id:  1428
No features found for file id:  1429
No features found for file id:  1430
No features found for file id:  1432
No features found for file id:  1433
No features found for file id:  1435
No features found for file id:  1436
No features found for file id:  1437
No features found for file id:  1438
No features found for file id:  1439
No features found for file id:  144
No features found for file id:  1440
No features found for file id:  1441
No features found for file id:  1442
No features found for file id:  1443
No features found for file id:  1444
No features found for file id:  1445
No features found for file id:  1447
No features found for file id:  1448
No features found for file id:  1449
No features found for file id:  145
No features found for file id:  1453
No features found for file id:  1454
No features found for file id:  1455
No features found for file id:  1458
No features found for file id:  1459
No features found for file id:  146
No features found for file id:  1460
No features found for file id:  1461
No features found for file id:  1465
No features found for file id:  1466
No features found for file id:  1467
No features found for file id:  1468
No features found for file id:  1469
No features found for file id:  1470
No features found for file id:  1471
No features found for file id:  1472
No features found for file id:  1473
No features found for file id:  1474
No features found for file id:  1475
No features found for file id:  1476
No features found for file id:  1477
No features found for file id:  1478
No features found for file id:  1479
No features found for file id:  1481
No features found for file id:  1482
No features found for file id:  1483
No features found for file id:  1486
No features found for file id:  1487
No features found for file id:  1489
No features found for file id:  149
No features found for file id:  1491
No features found for file id:  1492
No features found for file id:  1493
No features found for file id:  1494
No features found for file id:  1496
No features found for file id:  1499
No features found for file id:  15
No features found for file id:  1500
No features found for file id:  1501
No features found for file id:  1505
No features found for file id:  1506
No features found for file id:  1507
No features found for file id:  1508
No features found for file id:  1509
No features found for file id:  151
No features found for file id:  1510
No features found for file id:  1511
No features found for file id:  1512
No features found for file id:  1513
No features found for file id:  1514
No features found for file id:  1515
No features found for file id:  1516
No features found for file id:  1517
No features found for file id:  1518
No features found for file id:  1519
No features found for file id:  152
No features found for file id:  1520
No features found for file id:  1521
No features found for file id:  1522
No features found for file id:  1523
No features found for file id:  1526
No features found for file id:  1527
No features found for file id:  1528
No features found for file id:  1529
No features found for file id:  153
No features found for file id:  1530
No features found for file id:  1531
No features found for file id:  1532
No features found for file id:  1533
No features found for file id:  1534
No features found for file id:  1535
No features found for file id:  1536
No features found for file id:  1537
No features found for file id:  1538
No features found for file id:  1539
No features found for file id:  154
No features found for file id:  1540
No features found for file id:  1544
No features found for file id:  1545
No features found for file id:  1546
No features found for file id:  1548
No features found for file id:  1549
No features found for file id:  155
No features found for file id:  1550
No features found for file id:  1551
No features found for file id:  1552
No features found for file id:  1553
No features found for file id:  1555
No features found for file id:  1556
No features found for file id:  1559
No features found for file id:  156
No features found for file id:  1561
No features found for file id:  1562
No features found for file id:  1563
No features found for file id:  1564
No features found for file id:  1565
No features found for file id:  1566
No features found for file id:  1567
No features found for file id:  1568
No features found for file id:  1569
No features found for file id:  157
No features found for file id:  1570
No features found for file id:  1571
No features found for file id:  1572
No features found for file id:  1573
No features found for file id:  1574
No features found for file id:  1575
No features found for file id:  1576
No features found for file id:  1577
No features found for file id:  1578
No features found for file id:  1579
No features found for file id:  158
No features found for file id:  1580
No features found for file id:  1581
No features found for file id:  1582
No features found for file id:  1584
No features found for file id:  1585
No features found for file id:  1586
No features found for file id:  1587
No features found for file id:  1588
No features found for file id:  1589
No features found for file id:  159
No features found for file id:  1590
No features found for file id:  1591
No features found for file id:  1592
No features found for file id:  1593
No features found for file id:  1594
No features found for file id:  1596
No features found for file id:  1598
No features found for file id:  1599
No features found for file id:  16
No features found for file id:  160
No features found for file id:  1600
No features found for file id:  1602
No features found for file id:  1603
No features found for file id:  1604
No features found for file id:  1605
No features found for file id:  1607
No features found for file id:  1608
No features found for file id:  161
No features found for file id:  1610
No features found for file id:  1612
No features found for file id:  1613
No features found for file id:  1614
No features found for file id:  1615
No features found for file id:  1616
No features found for file id:  1619
No features found for file id:  162
No features found for file id:  1620
No features found for file id:  1621
No features found for file id:  1622
No features found for file id:  1625
No features found for file id:  1626
No features found for file id:  1627

In [9]:
print(len(rows), "rows extracted.")
df = pandas.DataFrame(rows)

2896 rows extracted.

In [10]:
df = df.set_index("file_id")
df.index = pandas.to_numeric(df.index, errors='coerce')
df = df.sort_index()
df.head()

,feature_found,avec_emo_comportementale,avec_cat_fierte,avec_emo_complexe,avec_cat_colere,avec_cat_joie,avec_cat_autre,avec_cat_tristesse,avec_emo,avec_cat_surprise,avec_emo_designee,avec_emo_base,avec_cat_peur,avec_cat_admiration,avec_emo_montree,avec_emo_suggeree,avec_cat_embarras,text
file_id,,,,,,,,,,,,,,,,,,
1,True,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,"C'est dingue, après tout ce temps, plus de 15 ..."
2,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Plutôt d'accord pour les SAV, c'est le but mêm..."
3,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Bordel.
4,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,J'avais tapé une longue réponse.
5,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Une fausse manip sur le téléphone, et hop, per..."

In [11]:
df['feature_found'].value_counts()

feature_found
False    2183
True      713
Name: count, dtype: int64

In [12]:
# Aperçu des features binaires pour les phrases avec au moins une feature
feature_cols = ALL_FEATURES
df[df['feature_found'] == True][['text'] + feature_cols].head(10)

,text,avec_emo_comportementale,avec_cat_fierte,avec_emo_complexe,avec_cat_colere,avec_cat_joie,avec_cat_autre,avec_cat_tristesse,avec_emo,avec_cat_surprise,avec_emo_designee,avec_emo_base,avec_cat_peur,avec_cat_admiration,avec_emo_montree,avec_emo_suggeree,avec_cat_embarras
file_id,,,,,,,,,,,,,,,,,
1,"C'est dingue, après tout ce temps, plus de 15 ...",1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0
7,Non pas de problème de ce côté là heureusement !,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0
8,Les violences étaient clairement motivées par ...,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
10,"A l'époque, si je comprends bien, tu t'identif...",0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
12,Je vois donc comment tu peux penser avoir reçu...,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
13,En quoi c'est putaclic ?,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
17,La colonisation et l'esclavage domestique fond...,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
22,La colonisation a accentué l'appauvrissement e...,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0
30,Donc j'espère vraiment que ton médecin a décla...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
40,Une petite pépite et ultra simple à prendre en...,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0

In [14]:
df.to_csv("corpus_emotyc_reddit_features.csv", index=True)